image: golang:1.16.0-buster

cache:
  paths:
    - /apt-cache
    - /go/src/gitlab.com
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test
  - release

unit_tests:
  stage: test
  script:
    - go test -v ./...

build_them:
  stage: build
  script:
    - ./.build-all
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - paymail-server-linux-amd64
      - paymail-server-windows-amd64
      - paymail-server-darwin-amd64

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - echo 'running release_job'
  release:
    description: 'Latest release'  # $EXTRA_DESCRIPTION must be defined
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
